# Generated by Django 6.0.6 on 2026-08-18 04:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("announcements", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="content",
            field=models.TextField(default=""),
        ),
    ]
