# Generated by Django 6.0.6 on 2026-07-07 17:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("communities", "0002_remove_community_admin_community_admins_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="communityadminapplication",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "pending")),
                fields=("applicant", "community"),
                name="unique_pending_application_per_applicant_community",
            ),
        ),
    ]
