# Generated by Django 6.0.3 on 2026-03-15 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Space",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("location_type", models.CharField(max_length=50)),
                ("date_added", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
