# Generated by Django 6.0.6 on 2026-06-04 20:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0001_initial"),
        ("communities", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="business",
            name="address",
        ),
        migrations.RemoveField(
            model_name="business",
            name="city",
        ),
        migrations.RemoveField(
            model_name="business",
            name="contact_email",
        ),
        migrations.RemoveField(
            model_name="business",
            name="contact_phone",
        ),
        migrations.CreateModel(
            name="BusinessBranch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("contact_phone", models.CharField(max_length=25)),
                ("contact_email", models.EmailField(max_length=254)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branches",
                        to="businesses.business",
                    ),
                ),
                (
                    "community",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="businesses",
                        to="communities.community",
                    ),
                ),
            ],
        ),
    ]
