# Generated by Django 6.0.6 on 2026-06-05 20:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("businesses", "0003_alter_business_owner"),
        ("communities", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="community",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="businesses",
                to="communities.community",
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="business",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="businessbranch",
            name="community",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="branches",
                to="communities.community",
            ),
        ),
    ]
