# Generated by Django 6.0.6 on 2026-07-27 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("businesses", "0004_business_community_business_rejection_reason_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="businessbranch",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="businessbranch",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
