# Generated by Django 6.0.6 on 2026-08-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("businesses", "0007_follow"),
    ]

    operations = [
        migrations.AddField(
            model_name="business",
            name="category",
            field=models.CharField(
                choices=[
                    ("food_and_dining", "Food & Dining"),
                    ("retail_and_shopping", "Retail & Shopping"),
                    ("health_and_wellness", "Health & Wellness"),
                    ("home_and_repair_services", "Home & Repair Services"),
                    ("professional_services", "Professional Services"),
                    ("education", "Education"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=30,
            ),
        ),
    ]
