# Generated by Django 6.0.3 on 2026-03-26 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="password_hash",
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("resident", "Resident"),
                    ("business owner", "Business Owner"),
                    ("admin", "Admin"),
                ],
                max_length=20,
            ),
        ),
    ]
