# Generated by Django 6.0.3 on 2026-03-27 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_user_is_staff"),
        ("communities", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="community_id",
        ),
        migrations.AddField(
            model_name="user",
            name="community",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="members",
                to="communities.community",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_staff",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("resident", "Resident"),
                    ("business owner", "Business Owner"),
                    ("community admin", "Community Admin"),
                    ("admin", "Admin"),
                ],
                max_length=20,
            ),
        ),
    ]
