# Generated by Django 6.0.6 on 2026-08-13 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_commentlike"),
    ]

    operations = [
        migrations.AddField(
            model_name="comment",
            name="takedown_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
